//! The whole server.
//!
//! It serves files and does nothing else — no engine, no session, no document.
//! The sound plays in the browser, so there is nothing here to keep between one
//! request and the next.
//!
//! **Everything is compiled in**, the same way the desktop binary has always
//! embedded its interface, and the way Akamai asked for it: no static-file
//! serving in front, no WASI filesystem to mount.
//!
//! **And everything text is stored gzipped**, because this component *is* the
//! web server and nothing sits in front of it to compress what it sends. See
//! `build.rs`, which does the compressing and generates the routing table from
//! the same list — so the bytes in the binary and the routes that serve them
//! cannot fall out of step.
//!
//! ── the interface ──
//!
//! `ui/port/` is the desktop build's interface, copied across whole. What
//! replaced the server is `local-server.js`, which swaps the global `fetch`.
//! See `docs/PORT.md`.
//!
//! It began byte-for-byte identical and no longer is: `app.js` differs by 206
//! lines and `index.html` by 106, almost all of it the rail rebuild and the
//! removal of tagging. `app.css` is still identical. The divergence is
//! deliberate and its boundary is written down — `docs/EDGE-PARITY.md` in the
//! desktop repository: the engine and the file formats stay level, the
//! interface is ours.

use spin_sdk::http::{IntoResponse, Request, Response};
use spin_sdk::http_component;
use std::io::Read;

// (route, bytes, content-type, is_gzipped) — generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/assets.rs"));

/// Does this client want gzip?
///
/// Every browser says yes and has for twenty years. `curl` without
/// `--compressed` says nothing at all, and a request that did not ask must not
/// be handed compressed bytes with a header and left to work it out — that is
/// how a `curl | sha256sum` check silently starts hashing a gzip stream.
fn takes_gzip(req: &Request) -> bool {
    req.header("accept-encoding")
        .and_then(|v| v.as_str())
        .map(|v| v.to_ascii_lowercase().contains("gzip"))
        .unwrap_or(false)
}

#[http_component]
fn handle(req: Request) -> anyhow::Result<impl IntoResponse> {
    let path = req.path();

    let Some(&(_, bytes, kind, gzipped)) = ASSETS.iter().find(|(r, ..)| *r == path) else {
        return Ok(Response::builder()
            .status(404)
            .header("content-type", "text/plain; charset=utf-8")
            .header("cache-control", "no-cache")
            .body("no such file in this build")
            .build());
    };

    let mut res = Response::builder();
    res.status(200)
        .header("content-type", kind)
        // **`no-cache`, until the URLs carry a hash.**
        //
        // Everything here really is immutable for the life of a deployment —
        // but the paths are not: `/engine.wasm` means one thing today and
        // another after the next build, at the same URL. A long `max-age` on
        // that is a browser holding last week's engine with no way to be told.
        //
        // Found the moment it was written: an hour's `max-age` on `/` served
        // the previous page straight back after a rebuild.
        //
        // `no-cache` is not "do not store" — it is "revalidate first", so a
        // 304 still costs nothing but the round trip. When the assets are
        // content-hashed, they become `immutable` and only the page stays here.
        .header("cache-control", "no-cache");

    if !gzipped {
        return Ok(res.body(bytes.to_vec()).build());
    }

    if takes_gzip(&req) {
        // The common path, and the whole point: the stored bytes go out as
        // they are. `vary` because a cache in front of this must not hand a
        // gzip body to a client that did not ask for one.
        return Ok(res
            .header("content-encoding", "gzip")
            .header("vary", "accept-encoding")
            .body(bytes.to_vec())
            .build());
    }

    // The rare path. Costs a decompression on a request that will not happen
    // from a browser, and keeps the server honest for everything else.
    let mut out = Vec::new();
    flate2::read::GzDecoder::new(bytes).read_to_end(&mut out)?;
    Ok(res.header("vary", "accept-encoding").body(out).build())
}
