//! The whole server.
//!
//! It serves files and does nothing else — no engine, no session, no document.
//! The sound plays in the browser, so there is nothing here to keep between one
//! request and the next.
//!
//! **Everything is compiled in**, the same way the desktop binary has always
//! embedded its interface, and the way Akamai asked for it: no static-file
//! serving in front, no WASI filesystem to mount.
//!
//! **And everything text is stored gzipped**, because this component *is* the
//! web server and nothing sits in front of it to compress what it sends. See
//! `build.rs`, which does the compressing and generates the routing table from
//! the same list — so the bytes in the binary and the routes that serve them
//! cannot fall out of step.
//!
//! ── the interface ──
//!
//! `ui/port/` is the desktop build's interface, copied across whole. What
//! replaced the server is `local-server.js`, which swaps the global `fetch`.
//! See `docs/PORT.md`.
//!
//! It began byte-for-byte identical and no longer is: `app.js` differs by 206
//! lines and `index.html` by 106, almost all of it the rail rebuild and the
//! removal of tagging. `app.css` is still identical. The divergence is
//! deliberate and its boundary is written down — `docs/EDGE-PARITY.md` in the
//! desktop repository: the engine and the file formats stay level, the
//! interface is ours.

use spin_sdk::http::{IntoResponse, Request, Response};
use spin_sdk::http_component;
use std::io::Read;

// (route, bytes, content-type, is_gzipped) — generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/assets.rs"));

/// Does this client want gzip?
///
/// Every browser says yes and has for twenty years. `curl` without
/// `--compressed` says nothing at all, and a request that did not ask must not
/// be handed compressed bytes with a header and left to work it out — that is
/// how a `curl | sha256sum` check silently starts hashing a gzip stream.
fn takes_gzip(req: &Request) -> bool {
    req.header("accept-encoding")
        .and_then(|v| v.as_str())
        .map(|v| v.to_ascii_lowercase().contains("gzip"))
        .unwrap_or(false)
}

/// Percent-decode a request path, if there is anything in it to decode.
///
/// The library keeps the names people gave their files — `piano pad sub.opus`,
/// `Inverted Clarity [2021-10-16 223741].opus` — because the name is what the
/// file list shows and a person chose it. A browser encodes those before they
/// reach here, so the table is matched against `/sounds/piano%20pad%20sub.opus`
/// and misses every sound with a space in it.
///
/// Returns `None` when there is no `%`, which is every request but these.
fn percent_decoded(path: &str) -> Option<String> {
    if !path.contains('%') {
        return None;
    }
    let hex = |c: u8| match c {
        b'0'..=b'9' => Some(c - b'0'),
        b'a'..=b'f' => Some(c - b'a' + 10),
        b'A'..=b'F' => Some(c - b'A' + 10),
        _ => None,
    };
    let raw = path.as_bytes();
    let mut out = Vec::with_capacity(raw.len());
    let mut i = 0;
    while i < raw.len() {
        match (raw.get(i), raw.get(i + 1).copied().and_then(hex), raw.get(i + 2).copied().and_then(hex)) {
            (Some(b'%'), Some(hi), Some(lo)) => {
                out.push((hi << 4) | lo);
                i += 3;
            }
            _ => {
                out.push(raw[i]);
                i += 1;
            }
        }
    }
    // A malformed escape that is not UTF-8 is not a route either.
    String::from_utf8(out).ok()
}

#[http_component]
fn handle(req: Request) -> anyhow::Result<impl IntoResponse> {
    let path = req.path();

    // Exact first, decoded second. Nothing in the table contains a `%`, so the
    // second pass only ever runs for a name that was encoded on the way here.
    let found = ASSETS.iter().find(|(r, ..)| *r == path).or_else(|| {
        percent_decoded(path).and_then(|d| ASSETS.iter().find(|(r, ..)| *r == d))
    });

    let Some(&(_, bytes, kind, gzipped)) = found else {
        return Ok(Response::builder()
            .status(404)
            .header("content-type", "text/plain; charset=utf-8")
            .header("cache-control", "no-cache")
            .body("no such file in this build")
            .build());
    };

    let mut res = Response::builder();
    res.status(200)
        .header("content-type", kind)
        // **`no-cache`, until the URLs carry a hash.**
        //
        // Everything here really is immutable for the life of a deployment —
        // but the paths are not: `/engine.wasm` means one thing today and
        // another after the next build, at the same URL. A long `max-age` on
        // that is a browser holding last week's engine with no way to be told.
        //
        // Found the moment it was written: an hour's `max-age` on `/` served
        // the previous page straight back after a rebuild.
        //
        // `no-cache` is not "do not store" — it is "revalidate first", so a
        // 304 still costs nothing but the round trip. When the assets are
        // content-hashed, they become `immutable` and only the page stays here.
        .header("cache-control", "no-cache");

    if !gzipped {
        return Ok(res.body(bytes.to_vec()).build());
    }

    if takes_gzip(&req) {
        // The common path, and the whole point: the stored bytes go out as
        // they are. `vary` because a cache in front of this must not hand a
        // gzip body to a client that did not ask for one.
        return Ok(res
            .header("content-encoding", "gzip")
            .header("vary", "accept-encoding")
            .body(bytes.to_vec())
            .build());
    }

    // The rare path. Costs a decompression on a request that will not happen
    // from a browser, and keeps the server honest for everything else.
    let mut out = Vec::new();
    flate2::read::GzDecoder::new(bytes).read_to_end(&mut out)?;
    Ok(res.header("vary", "accept-encoding").body(out).build())
}
