//! Compress every embedded asset at build time.
//!
//! ── why ──────────────────────────────────────────────────────────────────────
//!
//! This component *is* the web server, so nothing sits in front of it to
//! compress what it sends. It shipped 1.8 MB of uncompressed text on every cold
//! visit, on a CDN, which is the one place that is least forgivable.
//!
//! And it decided a design question. `babylon.js` is 8,258,950 bytes and twelve
//! visuals need it — Surfaces, Stage, and the ten grain arrangements. Embedding
//! it raw would have taken the component from 2 MB to about 10 MB, which was
//! enough to leave it out and leave those visuals dead. Gzipped it is 1,775,012
//! bytes, and the question stops being interesting.
//!
//! ── how ──────────────────────────────────────────────────────────────────────
//!
//! Each asset is gzipped into `OUT_DIR` and a table is generated beside it.
//! `lib.rs` includes both, so the bytes in the binary are the compressed ones
//! and the routing table is derived from the same list that produced them —
//! there is no second list to fall out of step.
//!
//! The list below stays explicit rather than walking a directory. A component
//! cannot walk a directory it does not have, and being able to read what ships
//! is worth more than being able to add a file without thinking about it.

use std::io::Write;

/// route, source (relative to this crate), content-type, and whether to compress.
///
/// Opus is already compressed — gzip gains nothing on it and costs a
/// decompression. Everything else is text or wasm, and both compress well.
const ASSETS: &[(&str, &str, &str, bool)] = &[
    ("/", "../ui/port/index.html", "text/html; charset=utf-8", true),
    ("/index.html", "../ui/port/index.html", "text/html; charset=utf-8", true),
    ("/app.js", "../ui/port/app.js", "text/javascript; charset=utf-8", true),
    ("/app.css", "../ui/port/app.css", "text/css; charset=utf-8", true),
    // The rail: its own file, and nothing else depends on it.
    ("/rail.js", "../ui/port/rail.js", "text/javascript; charset=utf-8", true),
    ("/rail.css", "../ui/port/rail.css", "text/css; charset=utf-8", true),
    // Opens a sound on arrival. Edge build only.
    ("/first-sound.js", "../ui/port/first-sound.js", "text/javascript; charset=utf-8", true),
    // Record: the window, and what it is dressed in.
    ("/record-modal.js", "../ui/port/record-modal.js", "text/javascript; charset=utf-8", true),
    ("/record-modal.css", "../ui/port/record-modal.css", "text/css; charset=utf-8", true),
    ("/theme-palettes.js", "../ui/port/theme-palettes.js", "text/javascript; charset=utf-8", true),
    ("/theme-derive.js", "../ui/port/theme-derive.js", "text/javascript; charset=utf-8", true),
    ("/grain-shapes.js", "../ui/port/grain-shapes.js", "text/javascript; charset=utf-8", true),
    ("/room-paint.js", "../ui/port/room-paint.js", "text/javascript; charset=utf-8", true),
    ("/ridge-data.js", "../ui/port/ridge-data.js", "text/javascript; charset=utf-8", true),
    ("/vis-registry.js", "../ui/port/vis-registry.js", "text/javascript; charset=utf-8", true),
    ("/room3d.js", "../ui/port/room3d.js", "text/javascript; charset=utf-8", true),
    ("/stage.js", "../ui/port/stage.js", "text/javascript; charset=utf-8", true),
    ("/ridge.js", "../ui/port/ridge.js", "text/javascript; charset=utf-8", true),
    ("/room-text.js", "../ui/port/room-text.js", "text/javascript; charset=utf-8", true),
    ("/mp4.js", "../ui/port/mp4.js", "text/javascript; charset=utf-8", true),
    ("/vis-gl.js", "../ui/port/vis-gl.js", "text/javascript; charset=utf-8", true),
    ("/video-export.js", "../ui/port/video-export.js", "text/javascript; charset=utf-8", true),
    // Babylon, vendored from the desktop build. Twelve visuals need it.
    ("/vendor/babylon.js", "../ui/port/vendor/babylon.js", "text/javascript; charset=utf-8", true),
    // The server, in the page.
    ("/local-server.js", "../ui/local-server.js", "text/javascript; charset=utf-8", true),
    // The granular engine, built for the browser rather than for WASI. Two
    // different wasm targets in one deployment, which is the whole architecture
    // in one line: this one is *served*, not run.
    (
        "/engine.wasm",
        "../engine/target/wasm32-unknown-unknown/release/audiolab_engine.wasm",
        "application/wasm",
        true,
    ),
    ("/sounds/manifest.json", "../sounds/manifest.json", "application/json", true),
    ("/sounds/tv-snips.opus", "../sounds/tv-snips.opus", "audio/ogg", false),
];

fn main() {
    let out = std::env::var("OUT_DIR").expect("OUT_DIR");
    let mut table = String::from(
        "// Generated by build.rs. Do not edit.\n\
         // (route, bytes, content-type, is_gzipped)\n\
         pub static ASSETS: &[(&str, &[u8], &str, bool)] = &[\n",
    );

    let mut raw_total = 0usize;
    let mut out_total = 0usize;

    for (i, (route, src, kind, compress)) in ASSETS.iter().enumerate() {
        println!("cargo:rerun-if-changed={src}");

        let bytes = std::fs::read(src)
            .unwrap_or_else(|e| panic!("build.rs cannot read {src}: {e}\n\
                 If this is engine.wasm, the engine has not been built yet — \
                 `spin build` builds it first, and `cargo build` here alone does not."));
        raw_total += bytes.len();

        let (payload, gz) = if *compress {
            let mut enc =
                flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
            enc.write_all(&bytes).expect("gzip");
            (enc.finish().expect("gzip finish"), true)
        } else {
            (bytes, false)
        };
        out_total += payload.len();

        // One file per asset rather than one blob, so a failure names the asset.
        let name = format!("asset_{i}.bin");
        std::fs::write(format!("{out}/{name}"), &payload).expect("write asset");

        table.push_str(&format!(
            "    ({route:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{name}\")), {kind:?}, {gz}),\n"
        ));
    }

    table.push_str("];\n");
    std::fs::write(format!("{out}/assets.rs"), table).expect("write table");

    println!("cargo:rerun-if-changed=build.rs");
    println!(
        "cargo:warning=embedded {} assets: {raw_total} bytes raw -> {out_total} bytes stored ({:.1}x)",
        ASSETS.len(),
        raw_total as f64 / out_total.max(1) as f64
    );
}
